# ==========================================
# Nan Discovers 配置文件
# ==========================================

# 网站基本信息
title: Nan Discovers
description: 关于物理、生活、城市和书。
lang: zh-CN
timezone: Asia/Shanghai


# GitHub Pages 地址
url: "https://enen1e23.github.io"
baseurl: "/my-discover-blog"

# 主题与插件
theme: minima

plugins:
  - jekyll-feed

# 顶部导航栏只显示“关于”
header_pages:
  - about.md

# 文章网址格式
permalink: /:categories/:title/

# 所有文章默认使用post模板
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
